"""
POLYMARKET ALPHA MODE - Core Models
=================================
Pydantic models for trades, markets, agents, and system state.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum
from uuid import uuid4


# ============================================
# ENUMS
# ============================================

class TradeDirection(str, Enum):
    BUY = "buy"
    SELL = "sell"


class TradeOutcome(str, Enum):
    YES = "yes"
    NO = "no"


class AgentVote(str, Enum):
    YES = "yes"
    NO = "no"
    ABSTAIN = "abstain"


class AgentType(str, Enum):
    FUNDAMENTALIST = "fundamentalist"
    SENTIMENT = "sentiment"
    RISK_MANAGER = "risk_manager"


class MarketStatus(str, Enum):
    ACTIVE = "active"
    RESOLVED = "resolved"
    PAUSED = "paused"


class LogLevel(str, Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    SUCCESS = "success"
    TRADE = "trade"


# ============================================
# MARKET MODELS
# ============================================

class Market(BaseModel):
    """Polymarket market representation."""
    id: str
    question: str
    description: Optional[str] = None
    end_date: Optional[datetime] = None
    status: MarketStatus = MarketStatus.ACTIVE
    yes_price: float = Field(ge=0, le=1)
    no_price: float = Field(ge=0, le=1)
    volume_24h: float = 0.0
    liquidity: float = 0.0
    tags: List[str] = Field(default_factory=list)
    
    @property
    def spread(self) -> float:
        """Calculate bid-ask spread."""
        return abs(1.0 - self.yes_price - self.no_price)


class WatchedMarket(BaseModel):
    """Market being monitored by the Sniper Scope."""
    market: Market
    trigger_price: Optional[float] = None
    trigger_direction: Optional[str] = None  # "above" or "below"
    added_at: datetime = Field(default_factory=datetime.utcnow)
    notes: Optional[str] = None


# ============================================
# TRADE MODELS
# ============================================

class TradeSignal(BaseModel):
    """Signal generated by agents for potential trade."""
    id: str = Field(default_factory=lambda: str(uuid4())[:8])
    market_id: str
    market_question: str
    direction: TradeDirection
    outcome: TradeOutcome
    confidence: float = Field(ge=0, le=1)
    suggested_size: float
    reasoning: str
    source: str  # Which agent/strategy generated this
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class Trade(BaseModel):
    """Executed trade record."""
    id: str = Field(default_factory=lambda: str(uuid4())[:8])
    market_id: str
    market_question: str
    direction: TradeDirection
    outcome: TradeOutcome
    size: float
    price: float
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    tx_hash: Optional[str] = None
    status: str = "pending"  # pending, confirmed, failed
    pnl: Optional[float] = None
    closed_at: Optional[datetime] = None


# ============================================
# AGENT MODELS
# ============================================

class AgentAnalysis(BaseModel):
    """Individual agent's analysis of a market."""
    agent_type: AgentType
    agent_name: str
    vote: AgentVote
    confidence: float = Field(ge=0, le=1)
    reasoning: str
    data_sources: List[str] = Field(default_factory=list)
    analysis_time_ms: int = 0
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class CouncilDecision(BaseModel):
    """Collective decision from the Council of Agents."""
    id: str = Field(default_factory=lambda: str(uuid4())[:8])
    market_id: str
    market_question: str
    analyses: List[AgentAnalysis]
    final_decision: AgentVote
    consensus_score: float  # Percentage of agents agreeing
    should_execute: bool
    recommended_direction: Optional[TradeDirection] = None
    recommended_outcome: Optional[TradeOutcome] = None
    recommended_size: Optional[float] = None
    summary: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    @property
    def votes_for(self) -> int:
        return sum(1 for a in self.analyses if a.vote == AgentVote.YES)
    
    @property
    def votes_against(self) -> int:
        return sum(1 for a in self.analyses if a.vote == AgentVote.NO)


# ============================================
# WHALE WATCHER MODELS
# ============================================

class WhaleActivity(BaseModel):
    """Detected whale trading activity."""
    wallet_address: str
    market_id: str
    market_question: str
    direction: TradeDirection
    outcome: TradeOutcome
    size: float
    price: float
    tx_hash: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    wallet_pnl_30d: Optional[float] = None
    wallet_win_rate: Optional[float] = None


class CopyTradeSignal(BaseModel):
    """Signal to copy a whale trade."""
    whale_activity: WhaleActivity
    recommended_size: float
    ai_agrees: bool
    ai_reasoning: str
    confidence: float = Field(ge=0, le=1)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# ============================================
# PORTFOLIO MODELS
# ============================================

class Position(BaseModel):
    """Current position in a market."""
    market_id: str
    market_question: str
    outcome: TradeOutcome
    shares: float
    avg_price: float
    current_price: float
    unrealized_pnl: float
    opened_at: datetime


class Portfolio(BaseModel):
    """Complete portfolio state."""
    total_value: float
    cash_balance: float
    positions: List[Position] = Field(default_factory=list)
    daily_pnl: float = 0.0
    total_pnl: float = 0.0
    win_rate: float = 0.0
    total_trades: int = 0
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# ============================================
# SYSTEM STATE MODELS
# ============================================

class LogEntry(BaseModel):
    """Entry for the AI monologue log."""
    id: str = Field(default_factory=lambda: str(uuid4())[:8])
    level: LogLevel
    message: str
    source: str  # Component that generated this log
    metadata: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class SystemState(BaseModel):
    """Overall system state for the dashboard."""
    is_running: bool = False
    agents_active: int = 0
    markets_watched: int = 0
    active_positions: int = 0
    pending_signals: int = 0
    last_trade_time: Optional[datetime] = None
    uptime_seconds: int = 0
    errors_24h: int = 0
